//! Daemon base modules extracted from agents-managerd.

// Keep the existing crate-root configuration path for moved modules.
pub use am_config as config;
pub use am_core;
pub use am_ports;

mod arc_app_impls;
mod quota_conversions;

pub mod codex_status;
pub mod agent_relay;
pub mod agy_remote;
pub mod agy_screen;
pub mod agy_support;
pub mod assets;
pub mod atomic_file;
pub mod attach;
pub mod background_hook;
pub mod background_loop;
pub mod bot_input;
pub mod bot_trash;
pub mod build_scheduler;
pub mod bulk_restart;
pub mod cache_clock;
pub mod capabilities;
pub mod capture;
pub mod cargo_shim;
pub mod changelog;
pub mod child_reconcile_safety;
pub mod child_runtime;
pub mod claude_live;
pub mod claude_mode;
pub mod codex_update;
pub mod composer_parse;
pub mod config_audit;
pub mod credential_spawn;
pub mod db;
pub mod exec_retry;
pub mod fork_ops;
pub mod git_sh;
pub mod github;
pub mod herdr;
pub mod herdr_maintenance;
pub mod herdr_shim;
pub mod herdr_unit;
pub mod herdr_update;
pub mod herdr_version;
pub mod home;
pub mod hook_body;
pub mod hook_cmd;
pub mod hook_inbox;
pub mod host_baseline;
pub mod hosts;
pub mod kids_cache;
pub mod kind_probe;
pub mod launch_rev;
pub mod lc_error;
pub mod linux_proc;
pub mod local_image;
pub mod local_sh;
pub mod login_assist;
pub mod login_prompt;
pub mod memproc;
pub mod memstat;
pub mod models;
pub mod outbox;
pub mod outbox_remote;
pub mod pane_identity;
pub mod pasted_content;
pub mod pending_question;
pub mod preview_bind;
pub mod primary_keep_warm;
pub mod private_files;
pub mod probe_ws;
pub mod prompt_cache;
pub mod prompt_suggestion;
pub mod quota;
pub mod quota_agy;
pub mod quota_claude;
pub mod quota_grok;
pub mod release_triage;
pub mod remote_health;
pub mod remote_purge;
pub mod remote_trash;
pub mod restart_coalesce;
pub mod restart_intents;
pub mod rewind;
pub mod session_paused;
pub mod shared_host;
pub mod shim_path;
pub mod shim_refresh;
pub mod spawn_hints;
pub mod statusline_cmd;
pub mod supervisor_inbox;
pub mod tools;
pub mod transcript_read;
pub mod trust;
pub mod trusted_open;
pub mod update_watch;
pub mod upstream_update;
pub mod ws_event;

#[cfg(any(test, feature = "test-hooks"))]
pub mod race_point;
