[package]
name = "am-config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_ignored = "0.1"
sha2 = "0.10"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
toml_edit = { version = "0.22", features = ["serde"] }
tracing = "0.1"

[dev-dependencies]
libc = "0.2"
tokio = { version = "1", features = ["full", "test-util"] }
ulid = "1"
